import {
  DEV_TO_BASE_PATH,
  DEV_TO_DEBUG_HTML_PATH,
  DEV_TO_DEBUG_JSON_PATH,
  DEV_TO_DISCOVERY_PATH,
  DEV_TO_LOADER_BASE_PATH,
  DEV_TO_LOADER_UMD_PATH,
  DEV_TO_NAMESPACE,
  DEV_TO_VUE_BASE_PATH,
  DEV_TO_VUE_CONTRACT_PATH,
  DEV_TO_VUE_EVENT_FULL_RELOAD,
  DEV_TO_VUE_EVENT_HMR_UPDATE,
  DEV_TO_VUE_INIT_PATH,
  DEV_TO_VUE_NAMESPACE,
  DEV_TO_VUE_RUNTIME_PATH,
} from '@dev-to/shared'

export const PLUGIN_NAME = `${DEV_TO_NAMESPACE}_${DEV_TO_VUE_NAMESPACE}` as const
export const PLUGIN_LOG_PREFIX = `[${DEV_TO_NAMESPACE}:${DEV_TO_VUE_NAMESPACE}]` as const

// Unified discovery paths
export const STABLE_BASE_PATH = DEV_TO_BASE_PATH
export const STABLE_DISCOVERY_PATH = DEV_TO_DISCOVERY_PATH
export const STABLE_DEBUG_HTML_PATH = DEV_TO_DEBUG_HTML_PATH
export const STABLE_DEBUG_JSON_PATH = DEV_TO_DEBUG_JSON_PATH

// Unified loader paths (framework-agnostic)
export const STABLE_LOADER_UMD_PATH = DEV_TO_LOADER_UMD_PATH
export const STABLE_LOADER_BASE_PATH = DEV_TO_LOADER_BASE_PATH

// Vue-specific paths
export const STABLE_VUE_BASE_PATH = DEV_TO_VUE_BASE_PATH
export const STABLE_CONTRACT_PATH = DEV_TO_VUE_CONTRACT_PATH
export const STABLE_INIT_PATH = DEV_TO_VUE_INIT_PATH
export const STABLE_VUE_RUNTIME_PATH = DEV_TO_VUE_RUNTIME_PATH

export const EVENT_FULL_RELOAD = DEV_TO_VUE_EVENT_FULL_RELOAD
export const EVENT_HMR_UPDATE = DEV_TO_VUE_EVENT_HMR_UPDATE
