import { PLUGIN_LOG_PREFIX, STABLE_CONTRACT_PATH } from './constants.js'
import { toSafeUmdName } from './libBuildUtils.js'

interface CreateLoaderUmdWrapperOptions {
  componentName: string
  origin: string
  contractEndpoint?: string
  vueLoaderUrl?: string
}

/**
 * Generate a lightweight UMD wrapper that uses @dev-to/vue-loader to load the component.
 * This wrapper depends on vue-loader UMD build being available.
 */
export function createLoaderUmdWrapper(options: CreateLoaderUmdWrapperOptions): string {
  const {
    componentName,
    origin,
    contractEndpoint = STABLE_CONTRACT_PATH,
    vueLoaderUrl = 'https://cdn.jsdelivr.net/npm/@dev-to/vue-loader@latest/dist/index.umd.js',
  } = options
  const globalName = toSafeUmdName(componentName)

  // Generate UMD wrapper code
  const code = `/**
 * UMD Loader Wrapper for component: ${componentName}
 * Global name: ${globalName}
 * Generated by ${PLUGIN_LOG_PREFIX}
 *
 * This wrapper automatically exports a Vue component that can be used in any Vue environment.
 * No need to manually integrate @dev-to/vue-loader.
 *
 * ============= Quick Start =============
 *
 * 1. Load Vue:
 *    <script src="https://unpkg.com/vue@3/dist/vue.global.prod.js"></script>
 *
 * 2. Load this wrapper:
 *    <script src="${origin}/__dev_to__/loader/${componentName}.js"></script>
 *
 * 3. Use as a Vue component:
 *
 *    // Option A: Direct Vue rendering
 *    const Component = window.${globalName};
 *    const app = Vue.createApp(Component);
 *    app.mount('#app');
 *
 *    // Option B: Register as a component in an existing app
 *    const app = Vue.createApp({});
 *    app.component('${componentName}', window.${globalName});
 *    app.mount('#app');
 *
 *    // Option C: Direct function call (legacy compatibility)
 *    window.${globalName}(document.getElementById('app'), { prop1: 'value1' })
 *      .then(app => console.log('Rendered'))
 *      .catch(err => console.error('Error:', err));
 *
 * ============= Features =============
 * ✓ Zero configuration required
 * ✓ Automatic Vue detection
 * ✓ Supports CommonJS, AMD, and global scope
 * ✓ Auto-loads VueLoader from CDN if needed
 * ✓ Works in any Vue 3 environment
 *
 * Note: Make sure Vue 3 is available globally.
 */
(function (root, factory) {
  if (typeof exports === 'object' && typeof module !== 'undefined') {
    // CommonJS
    factory(exports, require('vue'), require('@dev-to/vue-loader'));
  } else if (typeof define === 'function' && define.amd) {
    // AMD
    define(['exports', 'vue', '@dev-to/vue-loader'], factory);
  } else {
    // Browser globals
    var globalObj = typeof globalThis !== 'undefined' ? globalThis : (typeof self !== 'undefined' ? self : root);
    var tempExports = {};
    factory(tempExports, globalObj.Vue, globalObj.DevToVueLoader);
    globalObj.${globalName} = tempExports.default;
  }
})(this, function (exports, Vue, VueLoaderModule) {
  'use strict';

  var VueLoader = null;
  var loadingPromise = null;

  // Helper function to load a script dynamically
  function loadScript(src) {
    return new Promise(function(resolve, reject) {
      var script = document.createElement('script');
      script.src = src;
      script.onload = resolve;
      script.onerror = reject;
      document.head.appendChild(script);
    });
  }

  // Helper function to ensure VueLoader is loaded
  function ensureVueLoaderLoaded() {
    if (VueLoader) {
      return Promise.resolve();
    }

    if (!loadingPromise) {
      loadingPromise = (function() {
        // First, try to get VueLoader from the global scope
        if (typeof window !== 'undefined' && window.DevToVueLoader && window.DevToVueLoader.VueLoader) {
          VueLoader = window.DevToVueLoader.VueLoader;
          return Promise.resolve();
        }

        // If not available, load it from URL
        console.log('${PLUGIN_LOG_PREFIX} Loading @dev-to/vue-loader...');
        return loadScript(${JSON.stringify(vueLoaderUrl)})
          .then(function() {
            if (typeof window !== 'undefined' && window.DevToVueLoader && window.DevToVueLoader.VueLoader) {
              VueLoader = window.DevToVueLoader.VueLoader;
              console.log('${PLUGIN_LOG_PREFIX} VueLoader loaded successfully');
            } else {
              throw new Error('${PLUGIN_LOG_PREFIX} VueLoader not found after loading');
            }
          })
          .catch(function(error) {
            console.error('${PLUGIN_LOG_PREFIX} Failed to load VueLoader:', error);
            throw error;
          });
      })();
    }

    return loadingPromise;
  }

  // Try to get VueLoader from the module if available
  if (VueLoaderModule && VueLoaderModule.VueLoader) {
    VueLoader = VueLoaderModule.VueLoader;
  }

  // Component configuration
  var config = {
    origin: ${JSON.stringify(origin)},
    name: ${JSON.stringify(componentName)},
    contractEndpoint: ${JSON.stringify(contractEndpoint)}
  };

  /**
   * Render the component using VueLoader
   */
  function render(targetElement, componentProps) {
    if (!targetElement) {
      throw new Error('${PLUGIN_LOG_PREFIX} Target element is required');
    }

    if (!Vue || !Vue.createApp) {
      throw new Error('${PLUGIN_LOG_PREFIX} Vue 3 is not loaded');
    }

    // Ensure VueLoader is available before rendering
    return ensureVueLoaderLoaded().then(function() {
      if (!VueLoader) {
        throw new Error('${PLUGIN_LOG_PREFIX} VueLoader initialization failed');
      }

      // Create VueLoader component props
      var loaderProps = {
        origin: config.origin,
        name: config.name,
        contractEndpoint: config.contractEndpoint,
        componentProps: componentProps || {}
      };

      // Create a wrapper component that uses VueLoader
      var WrapperComponent = {
        name: '${componentName}Wrapper',
        setup: function() {
          return function() {
            return Vue.h(VueLoader, loaderProps);
          };
        }
      };

      // Render using Vue
      var app = Vue.createApp(WrapperComponent);
      app.mount(targetElement);

      return app;
    });
  }

  // Create a Vue component wrapper for the render function
  var ComponentWrapper = {
    name: '${componentName}',
    props: {
      componentProps: {
        type: Object,
        default: function() { return {}; }
      }
    },
    setup: function(props) {
      var containerRef = Vue.ref(null);
      var isFirstRender = Vue.ref(true);

      Vue.onMounted(function() {
        if (!containerRef.value) return;

        render(containerRef.value, props.componentProps).catch(function(err) {
          console.error('${PLUGIN_LOG_PREFIX} Failed to render ${componentName}:', err);
          console.error('${PLUGIN_LOG_PREFIX} Props:', props.componentProps);
        });

        if (isFirstRender.value) {
          isFirstRender.value = false;
          if (typeof console !== 'undefined' && console.info) {
            console.info(
              '%c${PLUGIN_LOG_PREFIX}%c Successfully loaded and rendered component: %c${componentName}',
              'color: #42b883; font-weight: bold;',
              'color: #64748b;',
              'color: #42b883; font-weight: bold;'
            );
          }
        }
      });

      Vue.watch(function() { return props.componentProps; }, function(newProps) {
        if (containerRef.value) {
          // Re-render with new props
          containerRef.value.innerHTML = '';
          render(containerRef.value, newProps).catch(function(err) {
            console.error('${PLUGIN_LOG_PREFIX} Failed to re-render ${componentName}:', err);
          });
        }
      }, { deep: true });

      return function() {
        return Vue.h('div', { ref: containerRef });
      };
    }
  };

  // Also allow direct function call for backwards compatibility
  ComponentWrapper.render = render;

  // Export the API
  exports.default = ComponentWrapper;
});
`

  return code
}
