import {
  DEV_TO_REACT_BASE_PATH,
  DEV_TO_REACT_CONTRACT_PATH,
  DEV_TO_REACT_DEBUG_HTML_PATH,
  DEV_TO_REACT_DEBUG_JSON_PATH,
  DEV_TO_REACT_EVENT_FULL_RELOAD,
  DEV_TO_REACT_EVENT_HMR_UPDATE,
  DEV_TO_REACT_INIT_PATH,
  DEV_TO_REACT_LOADER_BASE_PATH,
  DEV_TO_REACT_NAMESPACE,
  DEV_TO_REACT_REACT_RUNTIME_PATH,
} from '@dev-to/react-shared'

export const PLUGIN_NAME = DEV_TO_REACT_NAMESPACE
export const PLUGIN_LOG_PREFIX = `[${PLUGIN_NAME}]` as const

export const STABLE_BASE_PATH = DEV_TO_REACT_BASE_PATH
export const STABLE_CONTRACT_PATH = DEV_TO_REACT_CONTRACT_PATH
export const STABLE_INIT_PATH = DEV_TO_REACT_INIT_PATH
export const STABLE_REACT_RUNTIME_PATH = DEV_TO_REACT_REACT_RUNTIME_PATH
export const STABLE_DEBUG_HTML_PATH = DEV_TO_REACT_DEBUG_HTML_PATH
export const STABLE_DEBUG_JSON_PATH = DEV_TO_REACT_DEBUG_JSON_PATH
export const STABLE_LOADER_BASE_PATH = DEV_TO_REACT_LOADER_BASE_PATH

export const EVENT_FULL_RELOAD = DEV_TO_REACT_EVENT_FULL_RELOAD
export const EVENT_HMR_UPDATE = DEV_TO_REACT_EVENT_HMR_UPDATE
