import { PLUGIN_LOG_PREFIX, STABLE_CONTRACT_PATH } from './constants.js'
import { toSafeUmdName } from './libBuildUtils.js'

interface CreateLoaderUmdWrapperOptions {
  componentName: string
  origin: string
  contractEndpoint?: string
}

/**
 * Generate a lightweight UMD wrapper that uses @dev-to/react-loader to load the component.
 * This wrapper depends on react-loader UMD build being available.
 */
export function createLoaderUmdWrapper(options: CreateLoaderUmdWrapperOptions): string {
  const { componentName, origin, contractEndpoint = STABLE_CONTRACT_PATH } = options
  const globalName = toSafeUmdName(componentName)

  // Generate UMD wrapper code
  const code = `/**
 * UMD Loader Wrapper for component: ${componentName}
 * Global name: ${globalName}
 * Generated by ${PLUGIN_LOG_PREFIX}
 *
 * This wrapper uses @dev-to/react-loader to dynamically load and render the component.
 *
 * Usage:
 * 1. Load React and ReactDOM:
 *    <script crossorigin src="https://unpkg.com/react@18/umd/react.production.min.js"></script>
 *    <script crossorigin src="https://unpkg.com/react-dom@18/umd/react-dom.production.min.js"></script>
 *
 * 2. Load ReactLoader:
 *    <script src="https://cdn.jsdelivr.net/npm/@dev-to/react-loader@latest/dist/index.umd.js"></script>
 *
 * 3. Load this wrapper:
 *    <script src="${origin}/__dev_to_react__/loader/${componentName}.js"></script>
 *
 * 4. Render the component (returns a Promise):
 *    <div id="app"></div>
 *    <script>
 *      window.${globalName}.render(
 *        document.getElementById('app'),
 *        { prop1: 'value1', prop2: 'value2' }
 *      ).then(function(root) {
 *        console.log('Component rendered successfully');
 *      }).catch(function(error) {
 *        console.error('Failed to render component:', error);
 *      });
 *    </script>
 *
 * Note: ReactLoader will be automatically loaded from CDN if not already available.
 */
(function (root, factory) {
  if (typeof exports === 'object' && typeof module !== 'undefined') {
    // CommonJS
    factory(exports, require('react'), require('react-dom'), require('@dev-to/react-loader'));
  } else if (typeof define === 'function' && define.amd) {
    // AMD
    define(['exports', 'react', 'react-dom', '@dev-to/react-loader'], factory);
  } else {
    // Browser globals
    var globalObj = typeof globalThis !== 'undefined' ? globalThis : (typeof self !== 'undefined' ? self : root);
    factory((globalObj.${globalName} = {}), globalObj.React, globalObj.ReactDOM, globalObj.DevToReactLoader);
  }
})(this, function (exports, React, ReactDOM, ReactLoaderModule) {
  'use strict';

  var ReactLoader = null;
  var loadingPromise = null;

  // Helper function to load a script dynamically
  function loadScript(src) {
    return new Promise(function(resolve, reject) {
      var script = document.createElement('script');
      script.src = src;
      script.onload = resolve;
      script.onerror = reject;
      document.head.appendChild(script);
    });
  }

  // Helper function to ensure ReactLoader is loaded
  function ensureReactLoaderLoaded() {
    if (ReactLoader) {
      return Promise.resolve();
    }

    if (!loadingPromise) {
      loadingPromise = (function() {
        // First, try to get ReactLoader from the global scope
        if (typeof window !== 'undefined' && window.DevToReactLoader && window.DevToReactLoader.ReactLoader) {
          ReactLoader = window.DevToReactLoader.ReactLoader;
          return Promise.resolve();
        }

        // If not available, load it from CDN
        console.log('${PLUGIN_LOG_PREFIX} Loading @dev-to/react-loader from CDN...');
        return loadScript('https://cdn.jsdelivr.net/npm/@dev-to/react-loader@latest/dist/index.umd.js')
          .then(function() {
            if (typeof window !== 'undefined' && window.DevToReactLoader && window.DevToReactLoader.ReactLoader) {
              ReactLoader = window.DevToReactLoader.ReactLoader;
              console.log('${PLUGIN_LOG_PREFIX} ReactLoader loaded successfully');
            } else {
              throw new Error('${PLUGIN_LOG_PREFIX} ReactLoader not found after loading');
            }
          })
          .catch(function(error) {
            console.error('${PLUGIN_LOG_PREFIX} Failed to load ReactLoader:', error);
            throw error;
          });
      })();
    }

    return loadingPromise;
  }

  // Try to get ReactLoader from the module if available
  if (ReactLoaderModule && ReactLoaderModule.ReactLoader) {
    ReactLoader = ReactLoaderModule.ReactLoader;
  }

  // Component configuration
  var config = {
    origin: ${JSON.stringify(origin)},
    name: ${JSON.stringify(componentName)},
    contractEndpoint: ${JSON.stringify(contractEndpoint)}
  };

  /**
   * Render the component using ReactLoader
   */
  function render(targetElement, componentProps) {
    if (!targetElement) {
      throw new Error('${PLUGIN_LOG_PREFIX} Target element is required');
    }

    if (!React || !React.createElement) {
      throw new Error('${PLUGIN_LOG_PREFIX} React is not loaded');
    }

    if (!ReactDOM || !ReactDOM.createRoot) {
      throw new Error('${PLUGIN_LOG_PREFIX} ReactDOM is not loaded');
    }

    // Ensure ReactLoader is available before rendering
    return ensureReactLoaderLoaded().then(function() {
      if (!ReactLoader) {
        throw new Error('${PLUGIN_LOG_PREFIX} ReactLoader initialization failed');
      }

      // Create ReactLoader component props
      var loaderProps = {
        origin: config.origin,
        name: config.name,
        contractEndpoint: config.contractEndpoint,
        componentProps: componentProps || {}
      };

      // Render using ReactLoader
      var root = ReactDOM.createRoot(targetElement);
      root.render(React.createElement(ReactLoader, loaderProps));

      return root;
    });
  }

  // Export the API
  exports.render = render;
  exports.config = config;
  exports.default = { render: render, config: config };

  // Mark as ES module
  Object.defineProperty(exports, '__esModule', { value: true });
});
`

  return code
}
