import { PLUGIN_LOG_PREFIX, STABLE_CONTRACT_PATH } from './constants.js'
import { toSafeUmdName } from './libBuildUtils.js'

interface CreateLoaderUmdWrapperOptions {
  componentName: string
  origin: string
  contractEndpoint?: string
}

/**
 * Generate a lightweight UMD wrapper that dynamically loads and renders the component.
 * This does NOT depend on ReactLoader - it implements its own light loading logic.
 */
export function createLoaderUmdWrapper(options: CreateLoaderUmdWrapperOptions): string {
  const { componentName, origin, contractEndpoint = STABLE_CONTRACT_PATH } = options
  const globalName = toSafeUmdName(componentName)

  // Generate UMD wrapper code
  const code = `/**
 * UMD Loader Wrapper for component: ${componentName}
 * Global name: ${globalName}
 * Generated by ${PLUGIN_LOG_PREFIX}
 *
 * This is a lightweight wrapper that dynamically loads and renders the component
 * from the Vite dev server. No external dependencies required besides React/ReactDOM.
 *
 * Usage:
 * 1. Load React and ReactDOM:
 *    <script crossorigin src="https://unpkg.com/react@18/umd/react.production.min.js"></script>
 *    <script crossorigin src="https://unpkg.com/react-dom@18/umd/react-dom.production.min.js"></script>
 *
 * 2. Load this wrapper:
 *    <script src="${origin}/__dev_to_react__/loader/${componentName}.js"></script>
 *
 * 3. Render the component in your page:
 *    <div id="app"></div>
 *    <script>
 *      var Component = window.${globalName}.default;
 *      window.${globalName}.render(
 *        document.getElementById('app'),
 *        { props: 'here' }
 *      );
 *    </script>
 *
 * The component loader will be available as: window.${globalName}
 */
(function (root, factory) {
  if (typeof exports === 'object' && typeof module !== 'undefined') {
    // CommonJS
    factory(exports, require('react'), require('react-dom'));
  } else if (typeof define === 'function' && define.amd) {
    // AMD
    define(['exports', 'react', 'react-dom'], factory);
  } else {
    // Browser globals
    var globalObj = typeof globalThis !== 'undefined' ? globalThis : (typeof self !== 'undefined' ? self : root);
    var exp = {};
    factory(exp, globalObj.React, globalObj.ReactDOM);
    globalObj.${globalName} = exp;
  }
})(this, function (exports, React, ReactDOM) {
  'use strict';

  // Dynamic loader that fetches and renders component from Vite dev server
  var ComponentLoader = {
    origin: ${JSON.stringify(origin)},
    componentName: ${JSON.stringify(componentName)},
    contractEndpoint: ${JSON.stringify(contractEndpoint)},

    /**
     * Load contract to get component mapping
     */
    _loadContract: function() {
      if (this._contractPromise) {
        return this._contractPromise;
      }

      var self = this;
      this._contractPromise = import(this.origin + this.contractEndpoint)
        .then(function(contractModule) {
          return contractModule.DEV_TO_REACT_CONTRACT || contractModule.default;
        })
        .catch(function(error) {
          console.error('${PLUGIN_LOG_PREFIX} Failed to load contract:', error);
          throw error;
        });

      return this._contractPromise;
    },

    /**
     * Resolve component entry path from contract
     */
    _resolveComponentPath: function(contract) {
      var componentMap = contract.dev && contract.dev.componentMap;
      if (!componentMap) {
        throw new Error('${PLUGIN_LOG_PREFIX} No componentMap found in contract');
      }

      var entryPath = componentMap[this.componentName] || componentMap['*'];
      if (!entryPath) {
        throw new Error('${PLUGIN_LOG_PREFIX} Component "' + this.componentName + '" not found in componentMap');
      }

      return entryPath;
    },

    /**
     * Render the component into a target element
     */
    render: function(targetElement, props) {
      var self = this;
      if (!targetElement) {
        throw new Error('${PLUGIN_LOG_PREFIX} Target element not provided');
      }
      if (!React || !React.createElement) {
        throw new Error('${PLUGIN_LOG_PREFIX} React is not loaded');
      }

      // Load contract first to get correct component path
      return this._loadContract()
        .then(function(contract) {
          var componentPath = self._resolveComponentPath(contract);

          // Import the component from resolved path
          return import(self.origin + componentPath);
        })
        .then(function(module) {
          var Component = module.default || module[self.componentName];
          if (!Component) {
            throw new Error('${PLUGIN_LOG_PREFIX} Component not found in module');
          }

          // Render using the appropriate API
          var root;
          if (ReactDOM.createRoot) {
            // React 18+
            root = ReactDOM.createRoot(targetElement);
            root.render(React.createElement(Component, props || {}));
          } else if (ReactDOM.render) {
            // React 17 and below
            ReactDOM.render(React.createElement(Component, props || {}), targetElement);
          } else {
            throw new Error('${PLUGIN_LOG_PREFIX} ReactDOM.render or ReactDOM.createRoot not found');
          }

          return { root: root, component: Component };
        })
        .catch(function(error) {
          console.error('${PLUGIN_LOG_PREFIX} Failed to load component:', error);
          targetElement.innerHTML = '<div style="color: red; padding: 10px; border: 1px solid red; border-radius: 4px;">Failed to load component: ' + error.message + '</div>';
          throw error;
        });
    },

    /**
     * Get component config (for ESM usage)
     */
    getConfig: function() {
      return {
        origin: this.origin,
        name: this.componentName,
        contractEndpoint: this.contractEndpoint
      };
    }
  };

  // Export the loader as default and named
  exports.default = ComponentLoader;
  exports.${globalName} = ComponentLoader;

  // Mark as ES module
  Object.defineProperty(exports, '__esModule', { value: true });
});
`

  return code
}
