import { PLUGIN_LOG_PREFIX, STABLE_CONTRACT_PATH } from './constants.js'
import { toSafeUmdName } from './libBuildUtils.js'

interface CreateLoaderUmdWrapperOptions {
  componentName: string
  origin: string
  contractEndpoint?: string
  reactLoaderUrl?: string
}

/**
 * Generate a lightweight UMD wrapper that uses @dev-to/react-loader to load the component.
 * This wrapper depends on react-loader UMD build being available.
 */
export function createLoaderUmdWrapper(options: CreateLoaderUmdWrapperOptions): string {
  const {
    componentName,
    origin,
    contractEndpoint = STABLE_CONTRACT_PATH,
    reactLoaderUrl = 'https://cdn.jsdelivr.net/npm/@dev-to/react-loader@latest/dist/index.umd.js',
  } = options
  const globalName = toSafeUmdName(componentName)

  // Generate UMD wrapper code
  const code = `/**
 * UMD Loader Wrapper for component: ${componentName}
 * Global name: ${globalName}
 * Generated by ${PLUGIN_LOG_PREFIX}
 *
 * This wrapper automatically exports a React component that can be used in any React environment.
 * No need to manually integrate @dev-to/react-loader.
 *
 * ============= Quick Start =============
 *
 * 1. Load React and ReactDOM:
 *    <script crossorigin src="https://unpkg.com/react@18/umd/react.production.min.js"></script>
 *    <script crossorigin src="https://unpkg.com/react-dom@18/umd/react-dom.production.min.js"></script>
 *
 * 2. Load this wrapper:
 *    <script src="${origin}/__dev_to__/loader/${componentName}.js"></script>
 *
 * 3. Use as a React component:
 *
 *    // Option A: Direct React rendering
 *    const Component = window.${globalName};
 *    const root = ReactDOM.createRoot(document.getElementById('app'));
 *    root.render(React.createElement(Component, { prop1: 'value1' }));
 *
 *    // Option B: Use in JSX (if using Babel)
 *    const Component = window.${globalName};
 *    root.render(<Component prop1="value1" />);
 *
 *    // Option C: Direct function call (legacy compatibility)
 *    window.${globalName}(document.getElementById('app'), { prop1: 'value1' })
 *      .then(root => console.log('Rendered'))
 *      .catch(err => console.error('Error:', err));
 *
 * ============= Features =============
 * ✓ Zero configuration required
 * ✓ Automatic React/ReactDOM detection
 * ✓ Supports CommonJS, AMD, and global scope
 * ✓ Auto-loads ReactLoader from CDN if needed
 * ✓ Works in any React environment
 *
 * Note: Make sure React v18+ and react-dom/client are available globally.
 */
(function (root, factory) {
  if (typeof exports === 'object' && typeof module !== 'undefined') {
    // CommonJS
    factory(exports, require('react'), require('react-dom'), require('@dev-to/react-loader'));
  } else if (typeof define === 'function' && define.amd) {
    // AMD
    define(['exports', 'react', 'react-dom', '@dev-to/react-loader'], factory);
  } else {
    // Browser globals
    var globalObj = typeof globalThis !== 'undefined' ? globalThis : (typeof self !== 'undefined' ? self : root);
    var tempExports = {};
    factory(tempExports, globalObj.React, globalObj.ReactDOM, globalObj.DevToReactLoader);
    globalObj.${globalName} = tempExports.default;
  }
})(this, function (exports, React, ReactDOM, ReactLoaderModule) {
  'use strict';

  var ReactLoader = null;
  var loadingPromise = null;

  // Helper function to load a script dynamically
  function loadScript(src) {
    return new Promise(function(resolve, reject) {
      var script = document.createElement('script');
      script.src = src;
      script.onload = resolve;
      script.onerror = reject;
      document.head.appendChild(script);
    });
  }

  // Helper function to ensure ReactLoader is loaded
  function ensureReactLoaderLoaded() {
    if (ReactLoader) {
      return Promise.resolve();
    }

    if (!loadingPromise) {
      loadingPromise = (function() {
        // First, try to get ReactLoader from the global scope
        if (typeof window !== 'undefined' && window.DevToReactLoader && window.DevToReactLoader.ReactLoader) {
          ReactLoader = window.DevToReactLoader.ReactLoader;
          return Promise.resolve();
        }

        // If not available, load it from URL
        console.log('${PLUGIN_LOG_PREFIX} Loading @dev-to/react-loader...');
        return loadScript(${JSON.stringify(reactLoaderUrl)})
          .then(function() {
            if (typeof window !== 'undefined' && window.DevToReactLoader && window.DevToReactLoader.ReactLoader) {
              ReactLoader = window.DevToReactLoader.ReactLoader;
              console.log('${PLUGIN_LOG_PREFIX} ReactLoader loaded successfully');
            } else {
              throw new Error('${PLUGIN_LOG_PREFIX} ReactLoader not found after loading');
            }
          })
          .catch(function(error) {
            console.error('${PLUGIN_LOG_PREFIX} Failed to load ReactLoader:', error);
            throw error;
          });
      })();
    }

    return loadingPromise;
  }

  // Try to get ReactLoader from the module if available
  if (ReactLoaderModule && ReactLoaderModule.ReactLoader) {
    ReactLoader = ReactLoaderModule.ReactLoader;
  }

  // Component configuration
  var config = {
    origin: ${JSON.stringify(origin)},
    name: ${JSON.stringify(componentName)},
    contractEndpoint: ${JSON.stringify(contractEndpoint)}
  };

  /**
   * Render the component using ReactLoader
   */
  function render(targetElement, componentProps) {
    if (!targetElement) {
      throw new Error('${PLUGIN_LOG_PREFIX} Target element is required');
    }

    if (!React || !React.createElement) {
      throw new Error('${PLUGIN_LOG_PREFIX} React is not loaded');
    }

    if (!ReactDOM || !ReactDOM.createRoot) {
      throw new Error('${PLUGIN_LOG_PREFIX} ReactDOM is not loaded');
    }

    // Ensure ReactLoader is available before rendering
    return ensureReactLoaderLoaded().then(function() {
      if (!ReactLoader) {
        throw new Error('${PLUGIN_LOG_PREFIX} ReactLoader initialization failed');
      }

      // Create ReactLoader component props
      var loaderProps = {
        origin: config.origin,
        name: config.name,
        contractEndpoint: config.contractEndpoint,
        componentProps: componentProps || {}
      };

      // Render using ReactLoader
      var root = ReactDOM.createRoot(targetElement);
      root.render(React.createElement(ReactLoader, loaderProps));

      return root;
    });
  }

  // Create a React component wrapper for the render function
  function ComponentWrapper(props) {
    var containerRef = React.useRef(null);
    var isFirstRender = React.useRef(true);

    React.useEffect(function() {
      if (!containerRef.current) return;

      render(containerRef.current, props).catch(function(err) {
        console.error('${PLUGIN_LOG_PREFIX} Failed to render ${componentName}:', err);
        console.error('${PLUGIN_LOG_PREFIX} Props:', props);
      });

      if (isFirstRender.current) {
        isFirstRender.current = false;
        if (typeof console !== 'undefined' && console.info) {
          console.info(
            '%c${PLUGIN_LOG_PREFIX}%c Successfully loaded and rendered component: %c${componentName}',
            'color: #10b981; font-weight: bold;',
            'color: #64748b;',
            'color: #3b82f6; font-weight: bold;'
          );
        }
      }
    }, [props]);

    return React.createElement('div', { ref: containerRef });
  }

  // Export the API
  exports.default = ComponentWrapper;
});
`

  return code
}
